name: "Code Coverage Report "
description: "Comments a pull request with the pytest code coverage badge and full report"
author: "itsparser"
branding:
  icon: "message-circle"
  color: "purple"

inputs:
  repo-token:
    description: "GitHub API Access Token"
    default: ${{ github.token }}
    required: true

  configuration-path:
    description: "The location of the test config yml"
    default: ".github/test-config.yml"
    required: false

runs:
  using: "node16"
  main: "dist/index.js"
